name: Build
on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        uses: ./.github/actions/test
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}