name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '23'
          cache: 'maven'
          cache-dependency-path: 'pom.xml'
      - name: Build & test
        run: mvn verify
      - name: Report coverage
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: ${{ github.workspace }}/target/jacoco-report/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
#          min-coverage-overall: 40
#          min-coverage-changed-files: 60
          title: Code Coverage
          update-comment: true
      - name: Generate native image
        run: mvn package -Pnative
      - name: Set runner name
        id: runner-name
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require("fs");
            const files = fs.readdirSync("target");
            const runner = files.find(file => file.endsWith("-runner") || file.endsWith("-runner.exe"));
            const finalName = runner.replace(/(-runner)(.exe)?$/, '$2');
            core.setOutput('runner-file', runner);
            core.setOutput('final-name', finalName);
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.runner-name.outputs.final-name }}
          path: target/${{ steps.runner-name.outputs.runner-file }}
          overwrite: true