name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '23'
          cache: maven
          cache-dependency-path: 'pom.xml'
      - name: Build (no tests)
        run: mvn package -DskipTests -Pnative
      - name: list files
        run: ls -lR target/