name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '23'
          cache: 'maven'
          cache-dependency-path: 'pom.xml'
      - name: Build (no tests)
        run: mvn package -DskipTests -Pnative
      - name: List runner file
        id: runner-name
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require("fs");
            const files = fs.readdirSync("target");
            const runner = files.find(file => file.endsWith("runner") || file.endsWith("runner.exe"));
            const finalName = runner.slice(0,-7);
            core.setOutput('runner-file', runner);
            core.setOutput('final-name', finalName);
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.runner-name.outputs.final-name }}
          path: target/${{ steps.runner-name.outputs.runner-file }}
          overwrite: true