name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '23'
          cache: maven
          cache-dependency-path: 'pom.xml'
      - name: Build (no tests)
        run: mvn package -DskipTests -Pnative
      - name: Detect OS version
        run: mvn --version
#      - name: list files # TODO Delete later
#        run: ls -l target/quephaestus*
#      - name: move up
#        run: mv target/quephaestus*-runner ./
#      - name: rename artifact
#        run: mv quephaestus*-runner $(ls quephaestus*-runner | sed s/-runner//gi | sed)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: quephaestus-${{ runner.os }} # TODO this is really bad
          path: target/quephaestus*-runner
          overwrite: true


#      - name: Create Release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: Release ${{ github.ref }}
#          body: |
#            Changes in this Release
#            - First Change
#            - Second Change
#          draft: false
#          prerelease: false